language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t xkong93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xkong93/docker-react npm run test
